ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-dev.jaswanthdevops.online
CATALOGUE_HOST: catalogue-dev.jaswanthdevops.online
REDIS_HOST: redis-dev.jaswanthdevops.online
USER_HOST: user-dev.jaswanthdevops.online
CART_HOST: cart-dev.jaswanthdevops.online
MYSQL_HOST: mysql-dev.jaswanthdevops.online
SHIPPING_HOST: shipping-dev.jaswanthdevops.online
RABBITMQ_HOST: rabbitmq-dev.jaswanthdevops.online
PAYMENT_HOST: payment-dev.jaswanthdevops.online